# Generated by Django 4.1.3 on 2022-11-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('teamSize', models.IntegerField()),
                ('gameDuration', models.IntegerField()),
                ('goal', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
