# Generated by Django 4.1.3 on 2022-11-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='player_in_team',
        ),
        migrations.AddField(
            model_name='sport',
            name='players_in_team',
            field=models.IntegerField(default=5),
        ),
    ]
