# Generated by Django 2.0.2 on 2022-11-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_remove_sport_player_in_team_sport_players_in_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
