# Generated by Django 4.1.3 on 2022-11-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_auto_20221108_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
