# Generated by Django 4.1.4 on 2022-12-10 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0002_alter_games_hometeam_alter_games_roadteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='homeTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeTeam', to='basketball.teams', to_field='name', unique=True),
        ),
    ]
